### ISSUE TITLE
handleAllocBoxInst() in InstrKindInfoGetter causes segfault

### ISSUE THREAD

**Issue by gojeffcho** [uasys/swift#12]

**Comment by gojeffcho** [comment]
Was able to isolate this to ```VarDecl *decl``` and added a null check for it (line 137).

However, the null condition for decl is not handled, which must be added.

**Comment by aoli-al** [comment]
```
extension Collection {
  @_inlineable
  public func split() {

    func appendSubsequence() {
      var x = self.count
    }

      _ = appendSubsequence()
  }
}
```

This is the minimal test case that will crash the compiler. Hope this is helpful.

**Comment by karimhamdanali** [comment]
@Leeleo3x is that now fixed or is it still open?

**Comment by aoli-al** [comment]
@mmroz is working on this issue but I'd like to help Mark to solve this issue since he is busy with #22

**Comment by karimhamdanali** [comment]
gotcha! Thanks for chipping in.
