### ISSUE TITLE
Support Visit Enum Inst

### ISSUE THREAD

**Issue by mmroz** [uasys/swift#33]

**Comment by mmroz** [comment]
Given the Swift code:

enum Scalar {
    case emptyInput
}

var result : Scalar = .emptyInput

We get the WALA block:

FOO: 274579533:BLOCK
  LABEL_STMT
    "BLOCK #6"
    OBJECT_LITERAL
      "__DISCRIMINATOR__"
      "emptyInput"
  ASSIGN
    (null)
    (null)
  GOTO
    "BLOCK #7"

**Comment by karimhamdanali** [comment]
Shall we close this now?
