### ISSUE TITLE
Handle init_existential_addr instruction

### ISSUE THREAD

**Issue by bryantam** [uasys/swift#90]

**Comment by taufique71** [comment]
Duplicate of [Issue 82](https://github.com/themaplelab/swift/issues/82)

By the way I created several issues to work on in next few weeks. This (Issue 82) was one of them. But you can take it if you wish.

**Comment by bryantam** [comment]
Oops... duplicate again. I should be more careful. Thank you.
I have already finished implementing this and now cleaning up before making a PR. Would you mind closing yours?

**Comment by taufique71** [comment]
Sure. Closing [Issue 82](https://github.com/themaplelab/swift/issues/82) then.
